FROM node:24-alpine
WORKDIR /app
RUN apk add --no-cache inotify-tools
COPY package*.json ./
RUN npm ci
COPY tsconfig.json ./
COPY src/ ./src/
EXPOSE 5000 9229
ENV NODE_ENV=development
CMD ["npx", "ts-node", "--inspect=0.0.0.0:9229", "src/index.ts"]
